require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# This is a fairly static and thus safe master branch. (In the unlikely event that that changes, fork ;) )
source 'https://github.com/react-native-tvos/react-native-tvos-podspecs.git'
source 'https://github.com/bitmovin/cocoapod-specs.git'
source 'https://cdn.cocoapods.org/'

target 'RohTVApp' do

  platform :ios, '10.0'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RohTVAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RohTVApp-tvOS' do
  # Pods for RohTVApp-tvOS
  platform :tvos, '12.0'

  config = use_native_modules!

  # Hermes not yet available on tvOS
  use_react_native!(:path => config["reactNativePath"])

  pod 'BitmovinPlayer', '3.9.0'
  pod 'BitmovinAnalyticsCollector/Core', '2.4.0'
  pod 'BitmovinAnalyticsCollector/BitmovinPlayer', '2.4.0'
  
  target 'RohTVApp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end
