require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RohTVApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RohTVAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RohTVApp-tvOS' do
  # Pods for RohTVApp-tvOS
  platform :tvos, '12.0'

  config = use_native_modules!

  # Hermes not yet available on tvOS
  use_react_native!(:path => config["reactNativePath"])

  target 'RohTVApp-tvOSTests' do
    inherit! :complete
    # Pods for testing
  end

end
